apiVersion: v1
kind: Service
metadata:
  name: {{ include "apoe.fullname" . }}
  labels: {{- include "apoe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8085
  selector:
    app.kubernetes.io/name: apoe
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apoe.fullname" . }}-data
  labels: {{- include "apoe.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
